### ISSUE TITLE
Permisions denied usng informaticslab/goofys-flex-volume

### ISSUE THREAD

**Issue by guysoft** [informatics-lab/s3-fuse-flex-volume#16]
Hey,
Trying to use this chart, installed as provided in the README. 
Then created a deployment with a volume:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: selenium
  name: selenium
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: selenium
  template:
    metadata:
      labels:
        app.kubernetes.io/name: selenium
    spec:
      volumes:
      - name: goofys-mybucket
        flexVolume:
          driver: "informaticslab/goofys-flex-volume"
          options:
          # Required
          bucket: "xxxxxxxxxxxxxxx-eu"
          # Optional
          dirMode: "0755"
          fileMode: "0644"
          # uid: "501"
          # gid: "20"
          # subPath: "key/prefix"
          # endpoint: "s3.not-aws.com"
          # debug_s3: false
          # region: "us-east-1"
          access-key: "xxxxxxxxxxxxxxxxxxxx"
          secret-key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      containers:
      - image: XXXXXXX/selenium
        name: selenium
        imagePullPolicy: Always
        tty: true
        volumeMounts:
        - name: goofys-mybucket
          mountPath: /s3/mybucket
```

Also tried with and without dirMode/fileMode.

To run the deployment I also had to include ``--validate=false``
Because otherwise I get:
```
error: error validating "selenium-s3.yaml": error validating data: [ValidationError(Deployment.spec.template.spec.volumes[1].flexVolume): unknown field "access-key" in io.k8s.api.core.v1.FlexVolumeSource, ValidationError(Deployment.spec.template.spec.volumes[1].flexVolume): unknown field "bucket" in io.k8s.api.core.v1.FlexVolumeSource, ValidationError(Deployment.spec.template.spec.volumes[1].flexVolume): unknown field "dirMode" in io.k8s.api.core.v1.FlexVolumeSource, ValidationError(Deployment.spec.template.spec.volumes[1].flexVolume): unknown field "fileMode" in io.k8s.api.core.v1.FlexVolumeSource, ValidationError(Deployment.spec.template.spec.volumes[1].flexVolume): unknown field "secret-key" in io.k8s.api.core.v1.FlexVolumeSource]; if you choose to ignore these errors, turn validation off with --validate=false
```

If I bring it up and try to run ls I get "Permisions denied" to the volume, even as root.

What can I do to fix this?
Running with EKS 1.15.

**Comment by solovyevt** [comment]
Check your manifest, the section starting from `#Required` has a wrong indentation. It should something like this:

```
...
flexVolume:
  driver: "informaticslab/goofys-flex-volume"
  options:
    # Required
    bucket: "xxxxxxxxxxxxxxx-eu"
    # Optional
    dirMode: "0755"
    fileMode: "0644"
    # uid: "501"
    # gid: "20"
    # subPath: "key/prefix"
    # endpoint: "s3.not-aws.com"
    # debug_s3: false
    # region: "us-east-1"
    access-key: "xxxxxxxxxxxxxxxxxxxx"
    secret-key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
...
```
